name: Generate Snake Animation

on:
  schedule: # otomatis jalan tiap hari jam 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # bisa dijalankan manual juga

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: FebrianyRenata02
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: EndBug/add-and-commit@v9
        with:
          branch: output
          message: "Generate snake animation"
          add: "dist"
